### PR TITLE
Hello world project as one app with Webpack

### PR DESCRIPTION
**Pull request by batoorsohail**
### In this project we:

- [x] Created a new Rails app called 'hello-rails-react
     - Used the command rails new -j webpack my_new_rails_app
- [x] Created a babel.config.js in the root folder
- [x] Update webpack.config.js to include the babel loader
- [x] Created a table for storing your messages and create 5 different greetings
- [x] Created an API endpoint that selects a random greeting from your table
- [x] Created a static view
- [x] Created the App component with react-router
- [x] Created the Greeting component that will display a greeting
- [x] Created a store, an action, and a reducer that will connect to your API endpoint to get the random greeting
- [x] Display the random greeting in your Greeting component

### CODE REVIEW

**Review by christianbiring1 — CHANGES_REQUESTED** [review]
Hi @batoorsohail , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 

## Highlights
- [ ] Great work for setting your react on rails properly :+1: 
- [ ] Great work for setting your repo correctly :+1: 

## Required Changes ♻️
- [ ] Kindly make sure you fix this error in your app 
image

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by batoorsohail** [comment]
@christianbiring1 
Did you run this? I think if you run this it will work (at least in my case):
`npm install -g yarn`
`rake assets:precompile RAILS_ENV=production`

**Review by gemmen29 — APPROVED** [review]
Hi @batoorsohail, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 



## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by batoorsohail** [comment]
Thanks @gemmen29 😄

**Pull request merged**
